import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Seed dos artistas
  const artistsData = [
    { name: 'Sonnorum', is_casting_artist: false },
    { name: 'Zoldiex', is_casting_artist: false },
    { name: 'Andradz', is_casting_artist: false },
    { name: 'Vargazy', is_casting_artist: false },
    { name: 'Thomasi (BR)', is_casting_artist: false },
    { name: 'Brassed', is_casting_artist: false },
    { name: 'Serum', is_casting_artist: false },
    { name: 'Homanoff', is_casting_artist: false },
    { name: 'Slix', is_casting_artist: false },
    { name: 'C0rvo', is_casting_artist: false },
    { name: 'Moablive', is_casting_artist: false },
    { name: 'Reversemind', is_casting_artist: false },
    { name: 'Electric x', is_casting_artist: false },
    { name: 'Ullien', is_casting_artist: false },
    { name: 'Clark Bach', is_casting_artist: false },
    { name: 'Netrak', is_casting_artist: false },
    { name: 'ProjetoX', is_casting_artist: false },
    { name: 'Technical Intelligence', is_casting_artist: false },
    { name: 'Alien Dragons', is_casting_artist: false },
    { name: 'Go On', is_casting_artist: false },
    { name: 'CRUZ LIVE', is_casting_artist: false },
    { name: 'Hadaward', is_casting_artist: false },
    { name: 'Nauak (BR)', is_casting_artist: false },
    { name: 'Vitariom', is_casting_artist: false },
    { name: 'Tomasian', is_casting_artist: false },
    { name: 'Pelotero', is_casting_artist: false },
    { name: 'Deykiller', is_casting_artist: false },
    { name: 'LouAngs', is_casting_artist: false },
    { name: 'Deva BR', is_casting_artist: false },
    { name: 'Khronum', is_casting_artist: false },
    { name: 'Hypnus (BR)', is_casting_artist: false },
    { name: 'Bobeek', is_casting_artist: false },
    { name: 'Complex Side', is_casting_artist: false },
    { name: 'Alopez', is_casting_artist: false },
    { name: 'Lipe Du', is_casting_artist: false },
    { name: 'K.A.U', is_casting_artist: false },
    { name: 'Mazuk', is_casting_artist: false },
    { name: 'RITTER', is_casting_artist: false },
    { name: 'Klinx', is_casting_artist: false },
    { name: 'Rob Brainstorm', is_casting_artist: false },
    { name: 'Kauffman', is_casting_artist: false },
    { name: 'Hipoxya', is_casting_artist: false },
    { name: 'FM.GO', is_casting_artist: false },
    { name: 'GoaZio', is_casting_artist: false },
    { name: 'Pranksters', is_casting_artist: false },
    { name: 'Ale Vaz', is_casting_artist: false },
    { name: 'LUM1NA', is_casting_artist: false },
    { name: 'Mental Maze', is_casting_artist: false },
    { name: 'Le Klown', is_casting_artist: false },
    { name: 'Gauglitz', is_casting_artist: false },
    { name: 'Art Class', is_casting_artist: false },
    { name: 'FALK (BR)', is_casting_artist: false },
    { name: 'Bonne (BR)', is_casting_artist: false },
    { name: 'Tenet (BR)', is_casting_artist: false },
    { name: 'Inter.Act', is_casting_artist: false },
    { name: 'Claudinho Brasil', is_casting_artist: false },
    { name: 'Oluás', is_casting_artist: false },
    { name: 'Ethereal Fusion', is_casting_artist: false },
    { name: 'Dirty Distortion', is_casting_artist: false },
    { name: 'Venntury', is_casting_artist: false },
    { name: 'Egon', is_casting_artist: false },
    { name: 'Miirage', is_casting_artist: false },
    { name: 'Capteach', is_casting_artist: false },
    { name: 'Astral Traveler', is_casting_artist: false },
    { name: 'Ovnew', is_casting_artist: false },
    { name: 'Fractal Senses', is_casting_artist: false },
    { name: 'Continuo', is_casting_artist: false },
    { name: 'Crocoloko', is_casting_artist: false },
    { name: 'Harmonic7', is_casting_artist: false },
    { name: 'Sultanos', is_casting_artist: false },
    { name: 'Type7', is_casting_artist: false },
    { name: 'Sven (Brasil)', is_casting_artist: false },
    { name: 'Rooted', is_casting_artist: false },
  ];

  // Criar os artistas
  for (const artist of artistsData) {
    await prisma.artist.create({
      data: artist,
    });
  }

  // Seed dos releases
  const releasesData = [
    {
      music_name: 'Inner Fire',
      description: '',
      release_date: new Date('2024-05-27'),
      buy_link: 'https://www.beatport.com/track/inner-fire/19048317',
      cover_art: 'https://media.graphassets.com/resize=width:500/HOShM4QqSbeDnmghIis3',
      soundcloud_link: 'https://open.spotify.com/intl-pt/album/72W59mXa35SeG8e1NgREf7',
      spotify_link: 'https://open.spotify.com/intl-pt/album/72W59mXa35SeG8e1NgREf7',
      youtube_link: 'https://www.youtube.com/watch?v=BPH3ncXaYZU',
      deezer_link: 'https://www.deezer.com/pt/album/587245812',
      apple_link: 'https://music.apple.com/br/album/inner-fire-single/1746557010',
      slug: 'inner-fire',
      artists: ['Ale Vaz', 'Harmonic7'],
    },

    {
      music_name: 'Pleasure',
      description: '',
      release_date: new Date('2024-05-17'),
      buy_link: 'https://www.beatport.com/track/pleasure/19048293',
      cover_art: 'https://media.graphassets.com/resize=width:500/YnrccnO1QEi17yBWcvJm',
      soundcloud_link: 'https://open.spotify.com/intl-pt/track/22U6vTSexgEl8QZa5Ha9Pj',
      spotify_link: 'https://open.spotify.com/intl-pt/track/22U6vTSexgEl8QZa5Ha9Pj',
      youtube_link: 'https://www.youtube.com/watch?v=2JhcKIxxmRA',
      deezer_link: 'https://www.deezer.com/pt/album/587245702',
      apple_link: 'https://music.apple.com/br/album/pleasure-single/1746566031',
      slug: 'pleasure',
      artists: ['Dirty Distortion'],
    },

    {
      music_name: 'Understanding Space',
      description: '',
      release_date: new Date('2024-04-19'),
      buy_link: 'https://www.beatport.com/release/understanding-space/4539293',
      cover_art: 'https://media.graphassets.com/resize=width:500/egivVYsTKiwhGGduAhiQ',
      soundcloud_link: 'https://www.beatport.com/release/understanding-space/4539293',
      spotify_link: 'https://open.spotify.com/intl-pt/track/7aTe0tqxn5ni67LRkr1APn',
      youtube_link: 'https://www.youtube.com/watch?v=Tt9qN0QSv0M',
      deezer_link: 'https://www.deezer.com/pt/album/575044321',
      apple_link: 'https://music.apple.com/br/album/understanding-space-single/1741958952',
      slug: 'gau-undrstd-space',
      artists: ['Gauglitz'],
    },

    {
      music_name: 'Lost in Reality',
      description: '',
      release_date: new Date('2024-03-22'),
      buy_link: 'https://www.beatport.com/release/lost-in-reality/4489612',
      cover_art: 'https://media.graphassets.com/resize=width:500/sfOmW5OTQ3OMPjCZpudw',
      soundcloud_link: 'https://www.beatport.com/release/lost-in-reality/4489612',
      spotify_link: 'https://open.spotify.com/intl-pt/album/1wBPNFSYy8udNp9s3etyf2',
      youtube_link: 'https://www.youtube.com/watch?v=36wW5IW1DXM',
      deezer_link: 'https://www.deezer.com/pt/album/559260612',
      apple_link: 'https://music.apple.com/br/album/lost-in-reality-single/1735500218',
      slug: 'bobeek-lost-in-reality',
      artists: ['Bobeek'],
    },

    {
      music_name: 'Holding',
      description: '',
      release_date: new Date('2024-03-20'),
      buy_link: 'https://www.beatport.com/pt/artist/go-on/658600',
      cover_art: 'https://media.graphassets.com/resize=width:500/fpJRYq4BRcaKKxOwMnzq',
      soundcloud_link: 'https://www.beatport.com/pt/artist/go-on/658600',
      spotify_link: 'https://open.spotify.com/intl-pt/track/1C4pOFT8wBqg2hsiu15bo7',
      youtube_link: 'https://www.youtube.com/watch?v=8AIZ8aYW4bM',
      deezer_link: 'https://www.deezer.com/pt/album/560192032',
      apple_link: 'https://music.apple.com/br/album/holding-single/1735932656',
      slug: 'go-on-ovnew-holding',
      artists: ['Go On', 'Ovnew'],
    },

    {
      music_name: 'Everything Is Connected',
      description: '',
      release_date: new Date('2024-03-13'),
      buy_link: 'https://www.beatport.com/pt/track/everything-is-connected/18800429',
      cover_art: 'https://media.graphassets.com/resize=width:500/9wTvbrMSReq9yvBCn4Dr',
      soundcloud_link: 'https://www.youtube.com/watch?v=qFMMBb8MZtA',
      spotify_link: 'https://www.youtube.com/watch?v=qFMMBb8MZtA',
      youtube_link: 'https://www.youtube.com/watch?v=qFMMBb8MZtA',
      deezer_link: 'https://www.deezer.com/pt/album/559261282',
      apple_link: 'https://music.apple.com/br/album/everything-is-connected-single/1735503289',
      slug: 'everything-is-connected',
      artists: ['Mental Maze'],
    },

    {
      music_name: 'Cycles',
      description: '',
      release_date: new Date('2024-03-07'),
      buy_link: 'https://www.beatport.com/pt/release/cycles/4478487',
      cover_art: 'https://media.graphassets.com/resize=width:500/cApS1XqBQQqUMQMhI24R',
      soundcloud_link: 'https://soundcloud.com/astral-traveler-407740726/astral-traveler-cycles',
      spotify_link: 'https://open.spotify.com/intl-pt/track/00egEIFIgnuipB0ItVEBGx',
      youtube_link: 'https://www.youtube.com/watch?v=pCoYlq38I8I',
      deezer_link: 'https://www.deezer.com/pt/album/555961402',
      apple_link: 'https://music.apple.com/br/album/cycles-single/1734308500',
      slug: 'astral-traveler-cycles',
      artists: ['Astral Traveler'],
    },

    {
      music_name: 'Oriente',
      description: '',
      release_date: new Date('2024-02-29'),
      buy_link: 'https://www.beatport.com/pt/track/oriente/18718875',
      cover_art: 'https://media.graphassets.com/resize=width:500/VFwk1ksERBWqEViKpa9h',
      soundcloud_link: 'https://open.spotify.com/intl-pt/track/3VJvfpyeDZ3oY2GuhBiwAI',
      spotify_link: 'https://open.spotify.com/intl-pt/track/3VJvfpyeDZ3oY2GuhBiwAI',
      youtube_link: 'https://www.youtube.com/watch?v=b7wgzdH9OiQ',
      deezer_link: 'https://www.deezer.com/pt/album/550290752',
      apple_link: 'https://music.apple.com/br/album/oriente-single/1732020547',
      slug: 'goon-e-capteach-oriente',
      artists: ['Go On', 'Capteach'],
    },

    {
      music_name: 'Valley of Madness',
      description: '',
      release_date: new Date('2024-02-23'),
      buy_link: 'https://www.beatport.com/track/valley-of-madness/18727527',
      cover_art: 'https://media.graphassets.com/resize=width:500/WMeV7UkHSb6RDVh1ske6',
      soundcloud_link: 'https://www.beatport.com/track/valley-of-madness/18727527',
      spotify_link: 'https://open.spotify.com/intl-pt/track/6li1pX4R3o8y7EtgQXLUnK',
      youtube_link: 'https://www.youtube.com/watch?v=BFeznDm50rQ',
      deezer_link: 'https://www.deezer.com/pt/album/550958722',
      apple_link: 'https://music.apple.com/br/album/valley-of-madness-single/1732273922',
      slug: 'gau-valley-of-madness',
      artists: ['Gauglitz'],
    },

    {
      music_name: 'The Mission',
      description: '',
      release_date: new Date('2024-02-22'),
      buy_link: 'https://www.beatport.com/track/the-mission/18651990',
      cover_art: 'https://media.graphassets.com/resize=width:500/JSLKbYZaSTKZyjdtX1e9',
      soundcloud_link: 'https://www.deezer.com/pt/album/544114452',
      spotify_link: 'https://open.spotify.com/intl-pt/track/50H2kP9gcx11Fe8wm3obCs',
      youtube_link: 'https://www.youtube.com/watch?v=mJTa-zSOwVc',
      deezer_link: 'https://www.deezer.com/pt/album/544114452',
      apple_link: 'https://music.apple.com/br/album/the-mission-single/1729238880',
      slug: 'ale-vaz-e-reversemind-the-mission',
      artists: ['Ale Vaz', 'Reversemind'],
    },

    {
      music_name: 'Acid Trip',
      description: '',
      release_date: new Date('2024-02-16'),
      buy_link: 'https://www.beatport.com/pt/release/acid-trip/4448963',
      cover_art: 'https://media.graphassets.com/resize=width:500/WEFdPnFeRBqoNC305oDX',
      soundcloud_link: 'https://www.beatport.com/pt/release/acid-trip/4448963',
      spotify_link: 'https://open.spotify.com/intl-pt/track/4vimx95loKEUqc7CBMm0eW',
      youtube_link: 'https://www.youtube.com/watch?v=zpB4pO8Tc3Q',
      deezer_link: 'https://www.deezer.com/pt/album/547719022',
      apple_link: 'https://music.apple.com/br/album/acid-trip-single/1730745838',
      slug: 'miirage-acid-trip',
      artists: ['Miirage'],
    },

    {
      music_name: 'Namah Shiva',
      description: '',
      release_date: new Date('2024-02-06'),
      buy_link: 'https://www.beatport.com/release/namah-shiva/4402989',
      cover_art: 'https://media.graphassets.com/resize=width:500/oWbDXfpyT4W2MkTOEIw8',
      soundcloud_link: 'https://soundcloud.com/vennturyproject/venntury-namah-shiva-original',
      spotify_link: 'https://open.spotify.com/intl-pt/track/5yuraGzzp04QwJOUofvhhk',
      youtube_link: 'https://www.youtube.com/watch?v=qsd_fFr7_NM',
      deezer_link: 'https://deezer.page.link/fPrxYtx73xuPYPbd6',
      apple_link: 'https://music.apple.com/br/album/namah-shiva/1725172319?i=1725172320',
      slug: 'venntury-namah-shiva',
      artists: ['Venntury'],
    },

    {
      music_name: 'Spheres',
      description: '',
      release_date: new Date('2024-02-01'),
      buy_link: 'https://www.beatport.com/pt/track/spheres/18631353',
      cover_art: 'https://media.graphassets.com/resize=width:500/0J3FkLOSFeclVEK3Rfx0',
      soundcloud_link: 'https://open.spotify.com/intl-pt/album/1uSA0jd9dkoZ9I5meLK8eJ',
      spotify_link: 'https://open.spotify.com/intl-pt/album/1uSA0jd9dkoZ9I5meLK8eJ',
      youtube_link: 'https://www.youtube.com/watch?v=g_9HQtW2k9M',
      deezer_link: 'https://www.deezer.com/pt/album/541899722',
      apple_link: 'https://music.apple.com/br/album/spheres-single/1728290607',
      slug: 'pelotero-vs-egon-spheres',
      artists: ['Pelotero', 'Egon'],
    },

    {
      music_name: 'Frequency',
      description: '',
      release_date: new Date('2024-01-31'),
      buy_link: 'https://www.beatport.com/pt/track/frequency/18627301',
      cover_art: 'https://media.graphassets.com/resize=width:500/ZtWEyh9RSeecVuhB7Ro6',
      soundcloud_link: 'https://soundcloud.com/bonnesound/bonne-frequency',
      spotify_link: 'https://open.spotify.com/intl-pt/track/4pihidLkwtcDDfY1Evqjei',
      youtube_link: 'https://www.youtube.com/watch?v=-RJNgqzhmP4',
      deezer_link: 'https://www.deezer.com/pt/album/541546042',
      apple_link: 'https://music.apple.com/br/album/frequency-single/1728244109',
      slug: 'bonne-frequency',
      artists: ['Bonne'],
    },

    {
      music_name: 'My Only',
      description: '',
      release_date: new Date('2024-01-18'),
      buy_link: 'https://www.beatport.com/pt/track/my-only/18538421',
      cover_art: 'https://media.graphassets.com/resize=width:500/BzdeZLfQmpyR5tNmECoA',
      soundcloud_link: 'https://open.spotify.com/intl-pt/album/2M4lgifQKo6YjKySV0AG0W?si=3FWBh0MPQ-Gz7K7jXSFIlQ',
      spotify_link: 'https://open.spotify.com/intl-pt/album/2M4lgifQKo6YjKySV0AG0W?si=3FWBh0MPQ-Gz7K7jXSFIlQ',
      youtube_link: 'https://www.youtube.com/watch?v=55UBIT1zrn0',
      deezer_link: 'https://www.deezer.com/pt/album/532398542',
      apple_link: 'https://music.apple.com/br/album/my-only-single/1724745286',
      slug: 'alevaz-e-goon-my-only',
      artists: ['Ale Vaz', 'Go On'],
    },

    {
      music_name: 'Sweetheart',
      description: '',
      release_date: new Date('2023-12-07'),
      buy_link: 'https://www.beatport.com/pt/track/sweetheart/18438767',
      cover_art: 'https://media.graphassets.com/resize=width:500/JqlTo5pQySlIlho91jFZ',
      soundcloud_link: 'https://www.beatport.com/pt/track/sweetheart/18438767',
      spotify_link: 'https://open.spotify.com/intl-pt/album/32G1HRgx9U9HQnjOah220w',
      youtube_link: 'https://www.youtube.com/watch?v=ZryIomviY04',
      deezer_link: 'https://www.deezer.com/pt/album/520030102',
      apple_link: 'None',
      slug: 'sweetheart',
      artists: ['GO ON'],
    },

    {
      music_name: 'Dirty Way',
      description: '',
      release_date: new Date('2023-12-01'),
      buy_link: 'https://www.beatport.com/label/mushadelic-records/84164',
      cover_art: 'https://media.graphassets.com/resize=width:500/sWGFie7qRtGkti0IWj94',
      soundcloud_link: 'https://www.beatport.com/label/mushadelic-records/84164',
      spotify_link: 'https://open.spotify.com/intl-pt/track/1as2rrBFnS1B2xxt2Og1EZ',
      youtube_link: 'https://www.youtube.com/watch?v=XndjIAGan54',
      deezer_link: 'https://www.deezer.com/pt/album/517193892',
      apple_link: 'https://music.apple.com/br/album/dirty-way/1718575073?i=1718575074',
      slug: 'dirty-way',
      artists: ['Dirty Distortion'],
    },

    {
      music_name: 'Who Are U?',
      description: '',
      release_date: new Date('2023-11-28'),
      buy_link: 'https://www.beatport.com/pt/track/who-are-u/18412935',
      cover_art: 'https://media.graphassets.com/resize=width:500/SV6hc1VMQK6unwmiOPzi',
      soundcloud_link: 'https://soundcloud.com/gauglitzoficial/gauglitz-who-are-u-original-mix',
      spotify_link: 'https://open.spotify.com/intl-pt/album/6RUJlgzbBR3Y2FYLB8vaNK',
      youtube_link: 'https://www.youtube.com/watch?v=nbA74_HEHDU',
      deezer_link: 'https://www.deezer.com/pt/album/517193982',
      apple_link: 'https://music.apple.com/br/album/who-are-u-single/1718575258',
      slug: 'gauglitz-who-are-u',
      artists: ['Gauglitz'],
    },

    {
      music_name: 'Tengo',
      description: '',
      release_date: new Date('2023-11-23'),
      buy_link: 'https://www.beatport.com/track/tengo/18382483',
      cover_art: 'https://media.graphassets.com/resize=width:500/YLFq6yVoQs2DqLhUJ5G5',
      soundcloud_link: 'https://soundcloud.com/etherealfusionmusic/ethereal-fusion-tengo-original-mix-mushadelicrec',
      spotify_link: 'https://open.spotify.com/intl-pt/album/3tw5wmHwBtHzpwVkVcABbr',
      youtube_link: 'https://www.youtube.com/watch?v=45YZt7jSRLo',
      deezer_link: 'https://www.deezer.com/pt/album/514738272',
      apple_link: 'https://music.apple.com/br/album/tengo-single/1717406059',
      slug: 'ethereal-fusion-tengo',
      artists: ['Ethereal Fusion'],
    },

    {
      music_name: 'Shanti Connecto',
      description: '',
      release_date: new Date('2023-11-17'),
      buy_link: 'https://www.beatport.com/pt/track/shanti-connecto/18307608',
      cover_art: 'https://media.graphassets.com/resize=width:500/gfKqFkzRSnMRhKJrFLjI',
      soundcloud_link: 'https://www.beatport.com/pt/track/shanti-connecto/18307608',
      spotify_link: 'https://open.spotify.com/intl-pt/track/5joANg0KDbeQweNW2P2ObL',
      youtube_link: 'https://www.youtube.com/watch?v=NFY47CnS-z8',
      deezer_link: 'https://www.deezer.com/pt/album/507471731',
      apple_link: 'https://music.apple.com/br/album/shanti-connecto-single/1714516125',
      slug: 'shanti-connecto',
      artists: ['Claudinho Brasil', 'Oluás'],
    },

    {
      music_name: 'Dark Connected',
      description: '',
      release_date: new Date('2023-11-09'),
      buy_link: 'https://www.beatport.com/pt/release/dark-connected/4307878',
      cover_art: 'https://media.graphassets.com/resize=width:500/xCxx4tCDSpmS4KCO9enW',
      soundcloud_link: 'https://www.beatport.com/pt/release/dark-connected/4307878',
      spotify_link: 'https://open.spotify.com/intl-pt/album/1X4a9fEBDtq5JeUZR84nX4',
      youtube_link: 'https://www.youtube.com/watch?v=Ru2BavxbMSw',
      deezer_link: 'https://www.deezer.com/pt/album/501508761',
      apple_link: 'None',
      slug: 'deykiller-dark-connected',
      artists: ['Deykiller'],
    },

    {
      music_name: 'Through The Mirror',
      description: '',
      release_date: new Date('2023-11-07'),
      buy_link: 'https://www.beatport.com/pt/track/through-the-mirror/18245750',
      cover_art: 'https://media.graphassets.com/resize=width:500/do6cP3ahSfKL82JKD28L',
      soundcloud_link: 'https://soundcloud.com/falkmusic07/throug-the-mirror-1',
      spotify_link: 'https://open.spotify.com/intl-pt/track/4MhwcA7ZzzPc7cQGyE0wEo',
      youtube_link: 'https://www.youtube.com/watch?v=SbN8rEn82LA',
      deezer_link: 'https://www.deezer.com/pt/album/500449471',
      apple_link: 'None',
      slug: 'falk-through-the-mirror',
      artists: ['Falk'],
    },

    {
      music_name: 'Klownz',
      description: '',
      release_date: new Date('2023-11-02'),
      buy_link: 'https://www.beatport.com/release/klownz/4304378',
      cover_art: 'https://media.graphassets.com/resize=width:500/hXrZXru9T2aqqoQxY6nB',
      soundcloud_link: 'https://open.spotify.com/intl-pt/track/57bGbfg4sOKHpNdl5E27JZ',
      spotify_link: 'https://open.spotify.com/intl-pt/track/57bGbfg4sOKHpNdl5E27JZ',
      youtube_link: 'https://www.youtube.com/watch?v=U2jvw1TcwJA',
      deezer_link: 'https://www.deezer.com/pt/album/500449551',
      apple_link: 'https://music.apple.com/br/album/klownz/1711968556?i=1711968558',
      slug: 'pelotero-klownz',
      artists: ['Pelotero'],
    },

    {
      music_name: 'Something Real',
      description: '',
      release_date: new Date('2023-10-31'),
      buy_link: 'https://www.beatport.com/release/something-real/4322126',
      cover_art: 'https://media.graphassets.com/resize=width:500/qEQnpzcR9qIG5yXiPWQ0',
      soundcloud_link: 'https://soundcloud.com/inteact/interact-something-real-original-mix',
      spotify_link: 'https://open.spotify.com/intl-pt/track/6wsSZyr2UQvwIhbmW2LUlr',
      youtube_link: 'https://www.youtube.com/watch?v=FasWwyN20Tw',
      deezer_link: 'https://www.deezer.com/pt/album/506788721',
      apple_link: 'None',
      slug: 'interact-something-real',
      artists: ['Inter.Act'],
    },

    {
      music_name: 'Shai-Hulud',
      description: '',
      release_date: new Date('2023-10-26'),
      buy_link: 'https://www.beatport.com/release/shai-hulud/4312771',
      cover_art: 'https://media.graphassets.com/resize=width:500/cMe06VKHSrmPesmLDniZ',
      soundcloud_link: 'https://soundcloud.com/tenetdj/shai-hulud-1',
      spotify_link: 'https://open.spotify.com/intl-pt/track/2HHQPG4IJ1JOpES82wyKWz',
      youtube_link: 'https://www.youtube.com/watch?v=Qj8dSj1KIpY',
      deezer_link: 'https://www.deezer.com/pt/album/502848821',
      apple_link: 'https://music.apple.com/br/album/shai-hulud/1712898917?i=1712898918',
      slug: 'tenet-shai-hulud',
      artists: ['Tenet'],
    },

    {
      music_name: 'Moving Image',
      description: '',
      release_date: new Date('2023-10-19'),
      buy_link: 'https://www.beatport.com/release/moving-image/4304090',
      cover_art: 'https://media.graphassets.com/resize=width:500/c063eFk4S5qfVDpaWXiy',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/bonne-moving-image',
      spotify_link: 'https://open.spotify.com/intl-pt/track/5I5iOL19feg03tJ6bBZKw8',
      youtube_link: 'https://www.youtube.com/watch?v=Doam6RyarO4',
      deezer_link: 'https://www.deezer.com/pt/album/500298941',
      apple_link: 'None',
      slug: 'bonne-moving-image',
      artists: ['Bonne'],
    },

    {
      music_name: 'Altered State Of Consciousness',
      description: '',
      release_date: new Date('2023-09-14'),
      buy_link: 'https://www.beatport.com/pt/release/altered-state-of-consciousness/4263201',
      cover_art: 'https://media.graphassets.com/resize=width:500/PEZlmu6ERHu9rK3WXXpv',
      soundcloud_link: 'https://www.deezer.com/pt/album/486629505',
      spotify_link: 'https://open.spotify.com/intl-pt/album/4bZIucIM9gyiWBd2l2kE9m',
      youtube_link: 'https://www.youtube.com/watch?v=rfX5GRodKFc',
      deezer_link: 'https://www.deezer.com/pt/album/486629505',
      apple_link: 'https://music.apple.com/br/album/altered-state-of-consciousness-single/1706870437',
      slug: 'alien-dragons-asoc',
      artists: ['Alien Dragons'],
    },

    {
      music_name: 'Vorterix',
      description: '',
      release_date: new Date('2023-09-01'),
      buy_link: 'https://www.beatport.com/release/vorterix/4251006',
      cover_art: 'https://media.graphassets.com/resize=width:500/fNFDqzf2TneiSj1EtjsQ',
      soundcloud_link: 'https://soundcloud.com/deykiller/tracks',
      spotify_link: 'https://open.spotify.com/intl-pt/track/1XiDJZaHJOVlEMVF3P2t3s',
      youtube_link: 'https://www.youtube.com/watch?v=dhdaR-dGPf4&list=OLAK5uy_lM6cm-w0aTyjEA-vsgOhYBqpESYvGXEV4',
      deezer_link: 'None',
      apple_link: 'https://music.apple.com/br/album/vorterix-single/1705270818',
      slug: 'deykiller-vorteryx',
      artists: ['Deykiller'],
    },

    {
      music_name: 'Oppenheimer',
      description: '',
      release_date: new Date('2023-08-24'),
      buy_link: 'https://www.beatport.com/track/oppenheimer/18037295',
      cover_art: 'https://media.graphassets.com/resize=width:500/omSyM1qESbWQS0dL0cpp',
      soundcloud_link: 'https://www.beatport.com/track/oppenheimer/18037295',
      spotify_link: 'https://open.spotify.com/intl-pt/track/6X9Fjq58o2uwHo15d7twOe',
      youtube_link: 'https://www.youtube.com/watch?v=FVH0rncQ7fw',
      deezer_link: 'None',
      apple_link: 'https://music.apple.com/br/album/oppenheimer-single/1702516740',
      slug: 'go-og-oppenheimer',
      artists: ['Go On'],
    },

    {
      music_name: 'Getiopapa',
      description: '',
      release_date: new Date('2023-08-22'),
      buy_link: 'https://www.beatport.com/track/getiopapa/18053513',
      cover_art: 'https://media.graphassets.com/resize=width:500/fo0tUjcTLioIJY5FbPAV',
      soundcloud_link: 'https://www.beatport.com/track/getiopapa/18053513',
      spotify_link: 'https://open.spotify.com/intl-pt/track/5A11cy8PKZCsvGbfpoX4P8',
      youtube_link: 'https://www.youtube.com/watch?v=DjnI8syVuMk',
      deezer_link: 'None',
      apple_link: 'https://music.apple.com/br/album/getiopapa-single/1703263562',
      slug: 'alevaz-e-kauffman-getiopapa',
      artists: ['Ale Vaz', 'Kauffman'],
    },

    {
      music_name: 'Invencível ',
      description: '',
      release_date: new Date('2023-08-17'),
      buy_link: 'https://www.beatport.com/release/invencivel/4233245',
      cover_art: 'https://media.graphassets.com/resize=width:500/epvb9z3dSMKb4IxJvmML',
      soundcloud_link: 'https://soundcloud.com/artclass_music/art-class-invencivel',
      spotify_link: 'https://open.spotify.com/intl-pt/album/1F7wpCqSKYt3ns0QPUAB4O',
      youtube_link: 'https://www.youtube.com/watch?v=t0nzErvU_Lc',
      deezer_link: 'None',
      apple_link: 'https://music.apple.com/br/album/ashes-single/1511546103',
      slug: 'art-class-invencivel',
      artists: ['Art Class'],
    },

    {
      music_name: 'Cordyceps Funky',
      description: '',
      release_date: new Date('2023-08-10'),
      buy_link: 'https://www.beatport.com/release/cordyceps-funky/4203065',
      cover_art: 'https://media.graphassets.com/resize=width:500/WlYbIO1USdGEgv4SloO0',
      soundcloud_link: 'https://soundcloud.com/gauglitzoficial/gauglitz-cordyceps-funky-original-mix',
      spotify_link: 'https://open.spotify.com/intl-pt/track/1j1gOlWMwKxCXGIGOmPo2D',
      youtube_link: 'https://www.youtube.com/watch?v=LFDn1FwuCIs',
      deezer_link: 'https://www.deezer.com/pt/album/465812935',
      apple_link: 'https://music.apple.com/br/album/cordyceps-funky-single/1698338279',
      slug: 'gau-cordyceps-funky',
      artists: ['Gauglitz'],
    },

    {
      music_name: 'Brain Dead',
      description: '',
      release_date: new Date('2023-07-27'),
      buy_link: 'https://www.beatport.com/release/brain-dead/4203064',
      cover_art: 'https://media.graphassets.com/resize=width:500/S8q8e5HyRvCHTclgriQo',
      soundcloud_link: 'https://soundcloud.com/leklown/le-klown-brain-dead',
      spotify_link: 'https://open.spotify.com/intl-pt/album/6Ry1scnXbs8BmXUYrIf6d1',
      youtube_link: 'https://www.youtube.com/watch?v=BiXI3w4iT7Y',
      deezer_link: 'https://music.apple.com/br/album/brain-dead-single/1698345547',
      apple_link: 'https://music.apple.com/br/album/brain-dead-single/1698345547',
      slug: 'leklown-brain-dead',
      artists: ['LE KLOWN'],
    },

    {
      music_name: 'Revolução',
      description: '',
      release_date: new Date('2023-07-20'),
      buy_link: 'https://www.beatport.com/release/revolucao/4201116',
      cover_art: 'https://media.graphassets.com/resize=width:500/bxaBWtP4SsWx2i7gT6xn',
      soundcloud_link: 'https://soundcloud.com/homanoffmusic/revolucao-homanoff-e-mental-maze-original-mix',
      spotify_link: 'https://open.spotify.com/intl-pt/track/4AWZLtEe2svIoippeKwT3r',
      youtube_link: 'https://www.youtube.com/watch?v=X435qYhQfLI',
      deezer_link: 'https://www.deezer.com/pt/album/465812935',
      apple_link: 'https://music.apple.com/br/album/revolu%C3%A7%C3%A3o-single/1698121975',
      slug: 'homanoff-e-maze-revolucao',
      artists: ['Homanoff', 'Mental Maze'],
    },

    {
      music_name: 'About Love',
      description: '',
      release_date: new Date('2023-07-18'),
      buy_link: 'https://www.beatport.com/release/about-love/4201113',
      cover_art: 'https://media.graphassets.com/resize=width:500/hnkLP5gvQmSuUUpLaYJE',
      soundcloud_link: 'https://soundcloud.com/alevazmusic/ale-vaz-lum1na-about-love-original-mix',
      spotify_link: 'https://open.spotify.com/intl-pt/track/0QGZagTLtdTV1rpj2nl30Q',
      youtube_link: 'https://www.youtube.com/watch?v=PpXTfaXySMc',
      deezer_link: 'https://www.deezer.com/pt/album/465813135',
      apple_link: 'https://music.apple.com/br/album/about-love-single/1698128182',
      slug: 'about-love',
      artists: ['Ale Vaz', 'Lum1na'],
    },

    {
      music_name: 'Dont Look',
      description: '',
      release_date: new Date('2023-07-13'),
      buy_link: 'https://www.beatport.com/release/dont-look/4189507',
      cover_art: 'https://media.graphassets.com/resize=width:500/uj0VnVuCQnCkb8QqtlZY',
      soundcloud_link: 'https://soundcloud.com/prankstersdjs/pranksters-dont-look-original-mix',
      spotify_link: 'https://open.spotify.com/intl-pt/track/1zEDI2QAiILX2JZqvkaJTt',
      youtube_link: 'https://www.youtube.com/watch?v=pv9j7i2gG8c',
      deezer_link: 'https://www.deezer.com/pt/album/461720745',
      apple_link: 'https://music.apple.com/br/album/dont-look-single/1696149253',
      slug: 'pranks-dont-look',
      artists: ['Pranksters'],
    },

    {
      music_name: 'Wrath',
      description: '',
      release_date: new Date('2023-07-06'),
      buy_link: 'https://www.beatport.com/release/wrath/4183345',
      cover_art: 'https://media.graphassets.com/resize=width:500/YvLysiaJSjCFFBfPoSG2',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/pelotero-e-deykiller-wrath-original-mix',
      spotify_link: 'https://open.spotify.com/intl-pt/track/7su3Aqq1VWPO8sDBWB1xGv',
      youtube_link: 'https://www.youtube.com/watch?v=I6zxPGJuZzU',
      deezer_link: 'https://www.deezer.com/pt/album/460324325',
      apple_link: 'https://music.apple.com/br/album/wrath-single/1695552952',
      slug: 'pelota-e-dey-wrath',
      artists: ['Pelotero', 'Deykiller'],
    },

    {
      music_name: 'Paratti',
      description: '',
      release_date: new Date('2023-07-04'),
      buy_link: 'https://www.beatport.com/release/paratti/4180339',
      cover_art: 'https://media.graphassets.com/resize=width:500/tyKOAxIQDKErlvgA9RGX',
      soundcloud_link: 'https://soundcloud.com/fmgoa/fmgo-goazio-paratti-original-mix-16bit-master-02-06-2023',
      spotify_link: 'https://open.spotify.com/intl-pt/track/2uT9ncfmS9e8dmsg0X9z65',
      youtube_link: 'https://www.youtube.com/watch?v=WRCWrF66uio',
      deezer_link: 'https://www.deezer.com/pt/album/459197025',
      apple_link: 'https://music.apple.com/br/album/paratti-single/1694934887',
      slug: 'fmgo-goazio-paratti',
      artists: ['FM.GO', 'GoaZio'],
    },

    {
      music_name: 'Dancing Plants',
      description: '',
      release_date: new Date('2023-06-23'),
      buy_link: 'https://www.beatport.com/track/dancing-plants/17860521',
      cover_art: 'https://media.graphassets.com/resize=width:500/4tRhbJ3QFCl20kcsFMvn',
      soundcloud_link: 'https://soundcloud.com/hipoxya/hipoxya-dancing-plants',
      spotify_link: 'https://open.spotify.com/intl-pt/album/1aD4Xvmw06sRHVOhLzkTyR',
      youtube_link: 'https://www.youtube.com/watch?v=K5i9RFji2y8',
      deezer_link: 'https://www.deezer.com/pt/album/456014435',
      apple_link: 'https://music.apple.com/br/album/dancing-plants-single/1693663288',
      slug: 'hipoxya-danging-plants',
      artists: ['Hipoxya'],
    },

    {
      music_name: 'PROG CLUB (COMPILED BY MUSHADELIC RECORDS)',
      description: '',
      release_date: new Date('2023-06-14'),
      buy_link: 'https://www.beatport.com/release/prog-club-compiled-by-mushadelic-records/4143842',
      cover_art: 'https://media.graphassets.com/resize=width:500/ZOau5cHSRXydwrOkEFeb',
      soundcloud_link: 'https://open.spotify.com/intl-pt/album/5fTY2lFqbSy8AORCJylCiZ',
      spotify_link: 'https://open.spotify.com/intl-pt/album/5fTY2lFqbSy8AORCJylCiZ',
      youtube_link: 'https://www.youtube.com/watch?v=ZhnCR7SmZS4&list=OLAK5uy_lppFFSc_lxqyO9X757NT-8DgK_ljcBtiw',
      deezer_link: 'https://www.deezer.com/pt/album/446360995',
      apple_link: 'https://music.apple.com/br/album/prog-club-compiled-by-mushadelic-records-ep/1689759839',
      slug: 'va-prog-club',
      artists: ['Various Artists'],
    },

    {
      music_name: 'Alien Invasion',
      description: '',
      release_date: new Date('2023-05-31'),
      buy_link: 'https://www.beatport.com/release/alien-invasion/4141613',
      cover_art: 'https://media.graphassets.com/resize=width:500/Caagm2IVScelrGpRbLli',
      soundcloud_link: 'https://soundcloud.com/bobeekoficial/bobeek-alien-invasion-original-mix',
      spotify_link: 'https://open.spotify.com/intl-pt/track/7sckHfGyW8J94tMdzRbOkQ',
      youtube_link: 'https://www.youtube.com/watch?v=QlPQ9B2vhXw',
      deezer_link: 'https://www.deezer.com/pt/album/445755805',
      apple_link: 'https://music.apple.com/br/album/alien-invasion-single/1689461415',
      slug: 'bobeek-alien-ivasion',
      artists: ['Bobeek'],
    },

    {
      music_name: 'Crazy',
      description: '',
      release_date: new Date('2023-05-24'),
      buy_link: 'https://www.beatport.com/release/crazy/4122385',
      cover_art: 'https://media.graphassets.com/resize=width:500/4WZhYjaQzySHBrkbaJiE',
      soundcloud_link: 'https://soundcloud.com/hypnusbr/crazy-remix-hkmm1-1',
      spotify_link: 'https://open.spotify.com/track/68zMtm4SC4ZgR5ZTqVPPSa',
      youtube_link: 'https://www.youtube.com/watch?v=DoVKpQqmJbw',
      deezer_link: 'https://www.deezer.com/pt/album/438970457',
      apple_link: 'https://music.apple.com/br/album/crazy-single/1686959450',
      slug: 'hypnus-crazy',
      artists: ['Hypnus (BR)'],
    },

    {
      music_name: 'Primary Key',
      description: '',
      release_date: new Date('2023-05-03'),
      buy_link: 'https://www.beatport.com/track/primary-key/17654081',
      cover_art: 'https://media.graphassets.com/resize=width:500/Py50XwTS0uw4uCztRbEb',
      soundcloud_link: 'https://soundcloud.com/technical-intelligence/primary-key',
      spotify_link: 'https://open.spotify.com/album/107QMD0FytdcovZriK6Fqj',
      youtube_link: 'https://www.youtube.com/watch?v=fpseSkJCcAk',
      deezer_link: 'https://www.deezer.com/pt/album/433684437',
      apple_link: 'https://music.apple.com/br/album/primary-key-single/1684292303',
      slug: 'tech-int-primary-key',
      artists: ['Technical Intelligence'],
    },

    {
      music_name: 'Infinity Universe',
      description: '',
      release_date: new Date('2023-04-26'),
      buy_link: 'https://www.beatport.com/release/infinity-universe/4093917',
      cover_art: 'https://media.graphassets.com/resize=width:500/c7IwWQ8IT4avSIpTc8yN',
      soundcloud_link: 'https://soundcloud.com/edclivemusic/infinty-universe-hadawardoriginal-mix',
      spotify_link: 'https://open.spotify.com/album/5yVSmnJBeT1knx89ScQdUb',
      youtube_link: 'https://www.youtube.com/watch?v=_PnwBO_mgdo',
      deezer_link: 'https://www.deezer.com/pt/album/429747887',
      apple_link: 'https://music.apple.com/br/album/infinity-universe-single/1682371353',
      slug: 'hdw-infinity-universe',
      artists: ['Hadaward'],
    },

    {
      music_name: 'Journey',
      description: '',
      release_date: new Date('2023-04-12'),
      buy_link: 'https://www.beatport.com/release/journey/4084613',
      cover_art: 'https://media.graphassets.com/resize=width:500/vfqh0mkVTQKlfJPOTzIZ',
      soundcloud_link: 'https://soundcloud.com/khronum/journey',
      spotify_link: 'https://open.spotify.com/album/78dvlynTwPNJtW0TtIxY5z',
      youtube_link: 'https://www.youtube.com/watch?v=TWpaOpohqC0',
      deezer_link: 'https://www.deezer.com/pt/album/426146397',
      apple_link: 'https://music.apple.com/br/album/journey-single/1680897008',
      slug: 'krhonum-journey',
      artists: ['Khronum'],
    },

    {
      music_name: 'Pirka',
      description: '',
      release_date: new Date('2023-03-29'),
      buy_link: 'https://www.beatport.com/release/pirka/4073144',
      cover_art: 'https://media.graphassets.com/resize=width:500/Glw6ckAsTYqc9EWGN77M',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/tomasian-pirka',
      spotify_link: 'https://open.spotify.com/album/2l2APza946a0JuXo6AhpqL',
      youtube_link: 'https://www.youtube.com/watch?v=m-mFl5gPhfU',
      deezer_link: 'https://www.deezer.com/pt/album/422610977',
      apple_link: 'https://music.apple.com/br/album/pirka-single/1679371585',
      slug: 'tomasian-pirka',
      artists: ['Tomasian'],
    },

    {
      music_name: 'Hasta Morir',
      description: '',
      release_date: new Date('2023-03-01'),
      buy_link: 'https://www.beatport.com/track/hasta-morir/17415411',
      cover_art: 'https://media.graphassets.com/resize=width:500/uCTNNdmERDKbjeTXuAVC',
      soundcloud_link: 'https://on.soundcloud.com/S3Uqv',
      spotify_link: 'https://open.spotify.com/album/5HAgANAoLvtP87JVUSCvIg',
      youtube_link: 'https://www.youtube.com/watch?v=13blY5aSXAU',
      deezer_link: 'https://www.deezer.com/pt/album/407118737',
      apple_link: 'https://music.apple.com/br/album/hasta-morir-single/1671636552',
      slug: 'pelota-hasta-morrir',
      artists: ['Pelotero'],
    },

    {
      music_name: 'Mothership',
      description: '',
      release_date: new Date('2023-02-16'),
      buy_link: 'https://www.beatport.com/release/mothership/4020615',
      cover_art: 'https://media.graphassets.com/resize=width:500/LtqmxDRDSqGRQNouu5lN',
      soundcloud_link: 'https://on.soundcloud.com/mLbTp',
      spotify_link: 'https://open.spotify.com/album/1SVpllpn0EamuW50YNOOHS',
      youtube_link: 'https://www.youtube.com/watch?v=zctQtSfJ2E4',
      deezer_link: 'https://www.deezer.com/pt/album/405369187',
      apple_link: 'https://music.apple.com/br/album/mothership-single/1670673618',
      slug: 'alien-dragons-mothership',
      artists: ['Alien Dragons'],
    },

    {
      music_name: 'Never in the Past',
      description: '',
      release_date: new Date('2023-01-12'),
      buy_link: 'https://www.beatport.com/track/never-in-the-past/17356455',
      cover_art: 'https://media.graphassets.com/resize=width:500/PTtWI4VTLmIcl29LuYkH',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/go-on-nauak-br-never-in-the-past',
      spotify_link: 'https://open.spotify.com/album/5W0Qq7wBqTSznTgqUvSxvp',
      youtube_link: 'https://www.youtube.com/watch?v=s-RdTLA5Vco',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'go-on-nauak-br-never-in-the-past',
      artists: ['Go On', 'Nauak (BR)'],
    },

    {
      music_name: 'Circle',
      description: '',
      release_date: new Date('2022-12-23'),
      buy_link: 'https://www.beatport.com/track/circle/17356454',
      cover_art: 'https://media.graphassets.com/resize=width:500/DCQbFC8rQraSeTzi0HU0',
      soundcloud_link: 'https://soundcloud.com/edclivemusic/circle-hadaward-original-mix',
      spotify_link: 'https://open.spotify.com/album/0QrzOFIQidJ5qE0J3XGERl',
      youtube_link: 'https://www.youtube.com/watch?v=YSdZsRHDFPg',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'hadaward-circle',
      artists: ['Hadaward'],
    },

    {
      music_name: 'Seduction',
      description: '',
      release_date: new Date('2022-09-15'),
      buy_link: 'https://www.beatport.com/track/seduction/16911882',
      cover_art: 'https://media.graphassets.com/resize=width:500/pdPO6m6USmCJDbfld1Ed',
      soundcloud_link: 'https://soundcloud.com/cruzlive/cruz-seduction',
      spotify_link:
        'https://open.spotify.com/album/0jSnKuvkIR6uYIJS6bzfPS?highlight=spotify:track:102bZ4KMZsPGJH6oqAzc5R',
      youtube_link: 'https://www.youtube.com/watch?v=hc-vW_NLy9Y',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'cruz-seduction',
      artists: ['Cruz Live'],
    },

    {
      music_name: 'Chain Life',
      description: '',
      release_date: new Date('2022-09-01'),
      buy_link: 'https://www.beatport.com/track/chain-life/16878924',
      cover_art: 'https://media.graphassets.com/resize=width:500/wg9JpK0TgaprbEADfjtW',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/go-on-chain-life',
      spotify_link: 'https://open.spotify.com/album/5HWC5GMbJrY2qJ7bXXIvwf',
      youtube_link: 'https://open.spotify.com/album/5HWC5GMbJrY2qJ7bXXIvwf',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'go-on-chain-life',
      artists: ['Go On'],
    },

    {
      music_name: 'Cosmic Spirit',
      description: '',
      release_date: new Date('2022-07-21'),
      buy_link: 'https://www.beatport.com/release/cosmic-spirit/3813155',
      cover_art: 'https://media.graphassets.com/resize=width:500/OK4NoStxR9KoP8Li2SOc',
      soundcloud_link: 'https://soundcloud.com/aliendragons/alien-dragons-cosmic-mind',
      spotify_link: 'https://open.spotify.com/album/0JS9dnCEQWrOyrg7KWMBSC',
      youtube_link: 'https://open.spotify.com/album/0JS9dnCEQWrOyrg7KWMBSC',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'alien-drago-espirito-cosmico',
      artists: ['Alien Dragons'],
    },

    {
      music_name: 'Simulation',
      description: '',
      release_date: new Date('2022-07-01'),
      buy_link: 'https://www.beatport.com/track/simulation/17384412',
      cover_art: 'https://media.graphassets.com/resize=width:500/3TkDgBJRO4Vm7VS2PITA',
      soundcloud_link:
        'https://soundcloud.com/deykiller/deykiller-pelotero-simulation-master-by-technical-intelligence',
      spotify_link: 'https://open.spotify.com/album/4BZm0MOdPdQtZTiGUtvNf1',
      youtube_link: 'https://www.youtube.com/watch?v=CA6wL0m-CG4',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'pelota-e-deykiller-simulation',
      artists: ['Pelotero', 'Deykiller'],
    },

    {
      music_name: 'Reality',
      description: '',
      release_date: new Date('2022-06-21'),
      buy_link: 'https://www.beatport.com/track/reality/16653159',
      cover_art: 'https://media.graphassets.com/resize=width:500/2axR6dF0SpCOD1dumKhP',
      soundcloud_link:
        'https://soundcloud.com/technical-intelligence/reality?si=a8281de2dfe84de88c14c974e12edb23&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
      spotify_link: 'https://open.spotify.com/album/0G30tyGgWhloUZV2T3nOpF',
      youtube_link: 'https://www.youtube.com/watch?v=YG_CKTNP_v4',
      deezer_link: 'None',
      apple_link: 'https://music.apple.com/br/album/reality-single/1667941788',
      slug: 'technical-intelligence-reality',
      artists: ['Technical Intelligence'],
    },

    {
      music_name: 'Dark of Cachorrada?',
      description: '',
      release_date: new Date('2022-06-20'),
      buy_link: 'https://www.beatport.com/release/dark-or-cachorrada/4015234',
      cover_art: 'https://media.graphassets.com/resize=width:500/yg2EqTRRRJyc021lcQAi',
      soundcloud_link: 'https://soundcloud.com/anunnaki-rec/sets/brassed-live-dark-or',
      spotify_link: 'https://open.spotify.com/album/0EJQ0Wp8MMBlhOtZGK1KON',
      youtube_link: 'https://www.youtube.com/watch?v=idyPfpNDJpM',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'brassed-dark-or-doggy',
      artists: ['Brassed'],
    },

    {
      music_name: 'The Tribe - EP',
      description: '',
      release_date: new Date('2022-06-20'),
      buy_link: 'https://www.beatport.com/release/the-tribe/4015230',
      cover_art: 'https://media.graphassets.com/resize=width:500/koipRkQseQksbVxlKdzw',
      soundcloud_link: 'https://soundcloud.com/deykiller/sets/the-tribe',
      spotify_link: 'https://open.spotify.com/track/0p5RkXBgK3yNtUqGp2Y6AP',
      youtube_link: 'https://www.youtube.com/watch?v=1LkM8GQJFlg',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'the-tribe-deykiller',
      artists: ['Deykiller'],
    },

    {
      music_name: 'Embrace Darkness',
      description: '',
      release_date: new Date('2022-06-20'),
      buy_link: 'https://www.beatport.com/release/embrace-darkness/4015232',
      cover_art: 'https://media.graphassets.com/resize=width:500/0pz6ozI3Rr6mTLn5t5Y0',
      soundcloud_link: 'https://soundcloud.com/peloteropsy/pelotero-embrace-darkness-original-mix-anunnakirecords',
      spotify_link: 'https://open.spotify.com/track/3hNbtrQdhBgG9I97y7e6TZ',
      youtube_link: 'https://www.youtube.com/watch?v=aaxJYCAezyg',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'pelotero-embrace-darkness',
      artists: ['Pelotero'],
    },

    {
      music_name: 'Santa Psicodelia',
      description: '',
      release_date: new Date('2022-06-20'),
      buy_link: 'https://www.beatport.com/track/santa-psicodelia/17382501',
      cover_art: 'https://media.graphassets.com/resize=width:500/WG6W9rISWeEZTB0UdETK',
      soundcloud_link: 'https://soundcloud.com/mariano-tomasian/tomasian-santa-psicodelia',
      spotify_link: 'https://open.spotify.com/track/5LlLASflirwfBqNOOUQV02',
      youtube_link: 'https://www.youtube.com/watch?v=54HdfucPhEY',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'tomasian-santa-psicodelia',
      artists: ['Tomasian'],
    },

    {
      music_name: 'See You Now',
      description: '',
      release_date: new Date('2022-06-10'),
      buy_link: 'https://www.beatport.com/track/see-you-now/16630153',
      cover_art: 'https://media.graphassets.com/resize=width:500/Cl2pWBCRxWBjbBQtyORE',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/moab-projetox-see-you-now',
      spotify_link: 'https://open.spotify.com/track/2QQT62UqAJ3RewZ8ojA0oY',
      youtube_link: 'https://www.youtube.com/watch?v=Y3f80PWNb6I',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'moab-and-projetox-see-you-now',
      artists: ['Moablive', 'ProjetoX'],
    },

    {
      music_name: 'Focus And Concentration',
      description: '',
      release_date: new Date('2022-05-17'),
      buy_link: 'https://www.beatport.com/track/focus-and-concentration/17426531',
      cover_art: 'https://media.graphassets.com/resize=width:500/LiTnKQiSle9C7anon7kw',
      soundcloud_link: 'https://soundcloud.com/technical-intelligence/focus-and-concentration-original-mix',
      spotify_link: 'https://soundcloud.com/technical-intelligence/focus-and-concentration-original-mix',
      youtube_link: 'https://www.youtube.com/watch?v=1Rgc8-eEm8U',
      deezer_link: 'https://www.deezer.com/pt/album/408372077',
      apple_link: 'https://music.apple.com/br/album/focus-and-concentration/1672250389?i=1672250390',
      slug: 'technical-intelligence-focus-and-concentration',
      artists: ['Technical Intelligence'],
    },

    {
      music_name: 'Cant Wait',
      description: '',
      release_date: new Date('2021-12-09'),
      buy_link: 'https://www.beatport.com/track/cant-wait/16004966',
      cover_art: 'https://media.graphassets.com/resize=width:500/CJ2jZvb1TxWU2a7eMROP',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/netrak-cant-wait',
      spotify_link: 'https://open.spotify.com/track/5kpFjGwRdVjv41NOmgMD1z',
      youtube_link: 'https://www.youtube.com/watch?v=LmXwDEpR9uE',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'netrak-cant-wait',
      artists: ['Netrak'],
    },

    {
      music_name: 'Limited Future',
      description: '',
      release_date: new Date('2021-06-04'),
      buy_link: 'https://www.beatport.com/release/limited-future/3399556',
      cover_art: 'https://media.graphassets.com/resize=width:500/1QO0IjDHSti8LrltY7PW',
      soundcloud_link: 'https://soundcloud.com/ullien/sets/ep-limited-future',
      spotify_link: 'https://open.spotify.com/album/35xDo0rWxD8is8XAGPVCUw',
      youtube_link: 'https://www.youtube.com/watch?v=ThI5KXxS09Y',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'ullien-and-clark-limited-future',
      artists: ['Ullien', 'Clark Bach'],
    },

    {
      music_name: 'Artificial Gravity',
      description: '',
      release_date: new Date('2021-05-15'),
      buy_link: 'https://www.beatport.com/track/aritifical-gravity/15312165',
      cover_art: 'https://media.graphassets.com/resize=width:500/DFHrYws6R0BxfUBMpc43',
      soundcloud_link: 'https://soundcloud.com/rev3rsemind/reversemind-vs-electric-x-aritifical-gravity',
      spotify_link: 'https://open.spotify.com/album/30HWGYb9SVmkC5iI6dwvyp',
      youtube_link: 'https://www.youtube.com/watch?v=MHJEJ40eJ6Q',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'reversemind-and-electric-x-artificial-gravity',
      artists: ['Reversemind', 'Electric x'],
    },

    {
      music_name: 'Emperor',
      description: '',
      release_date: new Date('2021-04-10'),
      buy_link: 'https://www.beatport.com/track/emperor/15166109',
      cover_art: 'https://media.graphassets.com/resize=width:500/DWFDNUc9T1OtpKiBteih',
      soundcloud_link: 'https://soundcloud.com/moablive/emperor-original-mix',
      spotify_link: 'https://open.spotify.com/track/718ptTlXPPSfz7qjpzFet4',
      youtube_link: 'https://www.youtube.com/watch?v=Y3f80PWNb6I&list=OLAK5uy_mKp9bKNX3D5k7W8kCFG7TyqxddnEki43k',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'moablive-emperor',
      artists: ['Moablive'],
    },

    {
      music_name: 'Pure Evil',
      description: '',
      release_date: new Date('2021-03-13'),
      buy_link: 'https://www.beatport.com/track/pure-evil/15033800',
      cover_art: 'https://media.graphassets.com/resize=width:500/kFVeB9HXQh6ei0rWhHgy',
      soundcloud_link: 'https://soundcloud.com/c0rvomusic/c0rvo-pure-evil',
      spotify_link: 'https://open.spotify.com/album/2kg4C711vmtPhRozRl5vcJ',
      youtube_link: 'https://www.youtube.com/watch?v=9Xp_1nDl3os',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'corvo-pure-evil',
      artists: ['C0rvo'],
    },

    {
      music_name: 'Global Threat',
      description: '',
      release_date: new Date('2020-11-13'),
      buy_link: 'https://www.beatport.com/release/global-threat/3185759',
      cover_art: 'https://media.graphassets.com/resize=width:500/KlX2B1NLScufSCqkmeAf',
      soundcloud_link: 'https://soundcloud.com/c0rvomusic/c0rvo-global-threat-original-mix',
      spotify_link: 'https://open.spotify.com/album/5osRytHJFrQfXe2iDwnOaO',
      youtube_link: 'https://www.youtube.com/watch?v=UOKGNn-PKjg',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'corvo-global-threat',
      artists: ['C0rvo'],
    },

    {
      music_name: 'Apollo 11',
      description: '',
      release_date: new Date('2020-08-23'),
      buy_link: 'https://www.beatport.com/track/apollo-11/14094589',
      cover_art: 'https://media.graphassets.com/resize=width:500/FfwfdDRT6iTYqS8LQhYQ',
      soundcloud_link: 'https://soundcloud.com/slixlive/apollo11',
      spotify_link: 'https://open.spotify.com/album/465bF6yTPGKYJ0FB7ivUu6',
      youtube_link: 'https://www.youtube.com/watch?v=nE80Dz9UPLI',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'slix-and-brassed-apollo-11',
      artists: ['Slix', 'Brassed'],
    },

    {
      music_name: 'Object',
      description: '',
      release_date: new Date('2020-07-14'),
      buy_link: 'https://www.beatport.com/track/object/13933342',
      cover_art: 'https://media.graphassets.com/resize=width:500/Pm9Ja3tTRaKDjz7Githj',
      soundcloud_link: 'https://soundcloud.com/thomasimusic/thomasi-object-original',
      spotify_link:
        'https://open.spotify.com/album/2yuQ6i1AkjvXXec9EXnxnM?highlight=spotify:track:6xzVia8cJdXnyUtJ4rO2Nj',
      youtube_link: 'https://www.youtube.com/watch?v=5LF-tRDuPuo',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'thomasi-object',
      artists: ['Thomasi'],
    },

    {
      music_name: 'Purpose',
      description: '',
      release_date: new Date('2020-06-17'),
      buy_link: 'https://www.beatport.com/release/purpose/3015801',
      cover_art: 'https://media.graphassets.com/resize=width:500/igKVY1YkQZyTv82sUhl4',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/sets/homanoff-purpose-ep',
      spotify_link: 'https://open.spotify.com/album/6S316qNj5fx0u0bVISVYuv',
      youtube_link: 'https://open.spotify.com/album/6S316qNj5fx0u0bVISVYuv',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'homanoff-purpose',
      artists: ['Homanoff'],
    },

    {
      music_name: 'Iluminatti',
      description: '',
      release_date: new Date('2020-02-27'),
      buy_link: 'https://www.beatport.com/track/iluminatti/13232455',
      cover_art: 'https://media.graphassets.com/resize=width:500/H9w0KvBeTSCfxfIxEfME',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/serum-iluminatti-original-mix',
      spotify_link: 'https://open.spotify.com/album/3iMW4DdJjxuvV0cC9oWBSA',
      youtube_link: 'https://www.youtube.com/watch?v=GF9hSoKEgew',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'serum-iluminatti',
      artists: ['Serum'],
    },

    {
      music_name: 'Space Tribe',
      description: '',
      release_date: new Date('2020-02-27'),
      buy_link: 'https://www.beatport.com/track/space-tribe/13232537',
      cover_art: 'https://media.graphassets.com/resize=width:500/39x6xdauSpWE1jBAwmPR',
      soundcloud_link: 'https://soundcloud.com/brassedmusic/space-tribe-original-mix',
      spotify_link: 'https://open.spotify.com/album/4RBrSRvMb1dHulDmcbB483',
      youtube_link: 'https://www.youtube.com/watch?v=JXYPoT8N-y8',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'brassed-space-tribe',
      artists: ['Brassed'],
    },

    {
      music_name: 'L.S.D. Is The Bomb',
      description: '',
      release_date: new Date('2020-02-20'),
      buy_link: 'https://www.beatport.com/track/lsd-is-the-bomb/13201607',
      cover_art: 'https://media.graphassets.com/resize=width:500/3T5nFreeTDazowzbdkpz',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/vargazy-lsd-is-the-bomb',
      spotify_link: 'https://open.spotify.com/album/7nW0x3J9NVmHiX7ozUBPDO',
      youtube_link: 'https://www.youtube.com/watch?v=DuWkulJT5Ws',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'vargazy-lsd-is-the-bomb',
      artists: ['Vargazy'],
    },

    {
      music_name: 'Psychedelic Nature',
      description: '',
      release_date: new Date('2020-02-18'),
      buy_link: 'https://www.beatport.com/track/psychedelic-nature/13175467',
      cover_art: 'https://media.graphassets.com/resize=width:500/urhmFtcRiGOFxMtHGWQW',
      soundcloud_link: 'https://soundcloud.com/djandradz/psychedelic-nature',
      spotify_link: 'https://open.spotify.com/album/7LuxKTWjbsj8VBZY1DRZak?si=GQ5CIqodQISpRXNUE6aPVw&nd=1',
      youtube_link: 'https://www.youtube.com/watch?v=tMRMQJpWNSI',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'andradz-psychedelic-nature',
      artists: ['Andradz'],
    },

    {
      music_name: 'Lunar Eclipse',
      description: '',
      release_date: new Date('2020-02-11'),
      buy_link: 'https://www.beatport.com/track/lunar-eclipse/13134850',
      cover_art: 'https://media.graphassets.com/resize=width:500/1weK5E6QT25N0IceKrrb',
      soundcloud_link: 'https://soundcloud.com/mushadelicrec/zoldiex-lunar-eclipse',
      spotify_link: 'https://open.spotify.com/album/1RLYQfMjhFpTdGBZtGlVAF',
      youtube_link: 'https://www.youtube.com/watch?v=sb8loCa8zXA',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'zoldiex-lunar-eclipse',
      artists: ['Zoldiex'],
    },

    {
      music_name: 'Too Strong to Loose',
      description: '',
      release_date: new Date('2020-02-07'),
      buy_link: 'https://www.beatport.com/track/too-strong-to-lose/13127700',
      cover_art: 'https://media.graphassets.com/resize=width:500/y4fsDymdSOupSnBybVES',
      soundcloud_link: 'https://soundcloud.com/sonnorumlive/sonnorum-too-strong-to-lose',
      spotify_link: 'https://open.spotify.com/album/3tQyF7v8MtgfLqsOhhazCQ',
      youtube_link: 'https://music.youtube.com/watch?v=JSLjbQnjFSA&feature=share',
      deezer_link: 'None',
      apple_link: 'None',
      slug: 'sonnorum-too-strong-to-loose',
      artists: ['Sonnorum'],
    },
  ];

  // Criar os releases e associar com os artistas
  for (const releaseData of releasesData) {
    const artistIds = [];

    for (const artistName of releaseData.artists) {
      // Separar por '&' se houver múltiplos artistas
      const artistNames = artistName.split('&').map((name) => name.trim());

      for (const name of artistNames) {
        let artist = await prisma.artist.findFirst({
          where: { name },
        });

        // Se o artista não existir, cria o artista
        if (!artist) {
          artist = await prisma.artist.create({
            data: { name, is_casting_artist: false },
          });
        }

        artistIds.push(artist.id);
      }
    }

    // Criar o release e conectar todos os artistas encontrados
    await prisma.musicRelease.create({
      data: {
        music_name: releaseData.music_name,
        description: releaseData.description,
        release_date: releaseData.release_date,
        buy_link: releaseData.buy_link,
        cover_art: releaseData.cover_art,
        soundcloud_link: releaseData.soundcloud_link,
        spotify_link: releaseData.spotify_link,
        youtube_link: releaseData.youtube_link,
        deezer_link: releaseData.deezer_link,
        apple_link: releaseData.apple_link,
        slug: releaseData.slug,
        artists: {
          connect: artistIds.map((id) => ({ id })),
        },
      },
    });
  }
}

main()
  .then(async () => {
    console.log('Seed finished...');
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
